source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CollectionViewGridCalendarLayout', :exclusive => true do
  pod "CollectionViewGridCalendarLayout", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CollectionViewGridCalendarLayout", :path => "../"

  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
